
obj-${CONFIG_MACH_PDA}                += board-pda.o
obj-${CONFIG_MACH_PDA}                += board-pda-kbc.o
obj-${CONFIG_MACH_PDA}                += board-pda-sdhci.o
obj-${CONFIG_MACH_PDA}                += board-pda-power.o
obj-${CONFIG_MACH_PDA}                += board-atlantis-pda-power.o
obj-${CONFIG_MACH_PDA}                += board-pda-pinmux.o
obj-${CONFIG_MACH_PDA}                += board-pda-sensors.o
obj-${CONFIG_MACH_PDA}                += board-pda-panel.o
obj-${CONFIG_MACH_PDA}                += board-pda-memory.o
obj-${CONFIG_MACH_PDA}                += devices_lge.o
obj-${CONFIG_MACH_PDA}                += panel-l-720p-5.o
obj-${CONFIG_MACH_PDA}                += panel-j-720p-4-7.o
obj-${CONFIG_MACH_PDA}                += panel-s-1080p-5.o
obj-${CONFIG_MACH_PDA}                += panel-l-540p-4-7.o
obj-${CONFIG_MACH_PDA}                += lge_handle_panic.o
obj-${CONFIG_LGE_BLUETOOTH}                += bluetooth_pm.o